version: '3.8'

services:
  database:
    image: postgres
    container_name: tararau-bot-db
    restart: always
    # TODO remove ports when app is containerized
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=tararau-bot
    volumes:
      - pgdata:/data/postgres
    # TODO uncomment network_mode when app is containerized
    # network_mode: host
volumes:
  pgdata:
    driver: local
